### ISSUE TITLE
`docker-compose` group throwing access error

### ISSUE THREAD

**Issue by gabrielmccallin-tw** [nhsconnect/gpconnect-demonstrator#311]
I build the `gpconnect` image and run `docker-compose up`. There is a `docker-compose.yml` at the root of the project so I assume this is supported.

Startup log first error is this:
```
gpconnect-api_1  | 2020-01-23 16:45:08.660  WARN 1 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1044, SQLState: 42000
gpconnect-api_1  | 2020-01-23 16:45:08.660 ERROR 1 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Access denied for user 'gpconnectdbuser'@'%' to database 'gpconnect1'
```

Then `gpconnect-api` exits.

I did manage to get this setup working by renaming every `gpconnect1` database reference to `gpconnect` but this is somewhat heavy-handed. I can PR this changeset from a fork of the repo if required.

**Comment by SimonFarrowNHS** [comment]
I have asked someone with Docker experience to take a look at this.

**Comment by SimonFarrowNHS** [comment]
The Docker configs are old and rather experimental. There is some debate as to whether they worked at all.
We are currently very busy with release 1.3 at present and are not in a position to build or test any Docker deployments for some time. Meanwhile I would suggest amending the Dockerfile and *.yml to point to the new database schema name rather than changing the demonstrator to match the Docker configs.
That will be the fix I am aiming for when/if we have time to address.

**Comment by gabrielmccallin-tw** [comment]
👍

**Comment by SimonFarrowNHS** [comment]
Modified to ensure db names match the code.
