### ISSUE TITLE
Demonstrator improvements for swagger

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#40]
So there is data to be retrieved by the Swagger definition can we do the following:

- After the cleardown of appointments and slots overnight can we book two new appointments for patient "9476719931". If we can force the appointments created to have fixed logical ID that would be useful for the swagger read appointment example.

**Comment by lucywilcock** [comment]
Two new appointments will now be booked when the data is refreshed in the demonstrator database. 

These will be created for a patient with the NHS number saved under 'datasource.patient.nhsNumber' in the gpconnect-demonstrator-api.properties file. It will default to 9476719931. The appointments will be created for the first two slots in the database.

Because the id for the appointments table is auto-generated it overwrote anything I set manually. Instead, when the appointments table is cleared down the auto increment will now also be reset. This should not cause any problems as the table is empty at this point. The two saved appointments will then always be saved with ids 1 and 2.

**Comment by lucywilcock** [comment]
The code can be found in branch appointment-test-data

**Comment by lucywilcock** [comment]
This has been merged into develop and master and the 1.1.0 tag has been moved.

The sql has been updated manually for the public facing demonstrator and all three are displaying the auto-booked appointments,
